server:
  port: 58080

spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.67.113:3306/spring_blog
    username: spring_blog
    password: yuzaoqian123
  mail:
    host: smtp.qq.com
    port: 587
    username: wmrwkantskddhdmz@qq.com
    password: sqqdtqljorgrfbje
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
