server:
  port: 58080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23ligc4WFWPkukZwfD     # 替换为你的 Client ID
            client-secret: 4ee1c15d5a0da3e58b6de44240287667077f97e3   # 替换为你的 Client Secret
            redirect-uri: http://127.0.0.1:58080/login/oauth2/code/github
            scope:
              - read:user
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.67.113:3306/spring_blog
    hikari:
      username: spring_blog
      password: yuzaoqian123
      max-lifetime: 1800000         # 最大存活时间：30分钟
      idle-timeout: 600000          # 空闲连接超时时间：10分钟
      minimum-idle: 5               # 最小空闲连接数
      maximum-pool-size: 10         # 最大连接数
      keepalive-time: 60000         # 心跳间隔：60秒
      validation-timeout: 3000
      connection-test-query: SELECT 1
  mail:
    host: smtp.qq.com
    port: 465
    username: wmrwkantskddhdmz@qq.com
    password: sqqdtqljorgrfbje
    protocol: smtps
    smtp:
      auth: true
      ssl:
        enable: true
        trust: smtp.qq.com
      starttls:
        enable: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:13848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 28800
  application:
    name: ${spring.application.name}
    logger: slf4j
#    parameters:
#      instance:
#        port: ${server.port}
mybatis:
  mapper-locations: classpath:mapper/*.xml
