server:
  port: 58080

spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.67.113:3306/spring_blog
    username: spring_blog
    password: yuzaoqian123
  mail:
    host: smtp.qq.com
    port: 465
    username: wmrwkantskddhdmz@qq.com
    password: sqqdtqljorgrfbje
    protocol: smtps
    smtp:
      auth: true
      ssl:
        enable: true
        trust: smtp.qq.com
      starttls:
        enable: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
